"""add ai_challenges table

Revision ID: 03bdf2d7f0c4
Revises: 1bd970c16589
Create Date: 2026-06-11 16:06:23.803911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bdf2d7f0c4'
down_revision: Union[str, None] = '1bd970c16589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_target', sa.Float(), nullable=False),
    sa.Column('metric_package', sa.String(length=200), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', 'EXPIRED', name='challengestatus'), nullable=False),
    sa.Column('reward_type', sa.Enum('RUPEE_PAYOUT', 'MERCY_TOKEN', 'MULTIPLIER_BOOST', name='rewardtype'), nullable=False),
    sa.Column('reward_value', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('ai_rationale', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_challenges')
    # ### end Alembic commands ###
