"""add sleep_multiplier to daily_stats

Revision ID: 1bd970c16589
Revises: f4351477f291
Create Date: 2026-06-11 16:03:50.484979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd970c16589'
down_revision: Union[str, None] = 'f4351477f291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('sleep_multiplier', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_stats', 'sleep_multiplier')
    # ### end Alembic commands ###
