"""initial schema

Revision ID: 30033544869b
Revises: None
Create Date: 2026-06-11 08:38:51.985097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30033544869b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hourly_earn_rate', sa.Integer(), nullable=False),
    sa.Column('daily_target_hours', sa.Float(), nullable=False),
    sa.Column('lazy_tax_amount', sa.Integer(), nullable=False),
    sa.Column('lazy_tax_threshold_pct', sa.Float(), nullable=False),
    sa.Column('step_income_cap', sa.Integer(), nullable=False),
    sa.Column('monthly_budget', sa.Integer(), nullable=False),
    sa.Column('default_interest_rate', sa.Float(), nullable=False),
    sa.Column('study_hours_start', sa.Integer(), nullable=False),
    sa.Column('study_hours_end', sa.Integer(), nullable=False),
    sa.Column('unlock_tax_amount', sa.Integer(), nullable=False),
    sa.Column('salary_day_of_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss_fights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_hours', sa.Float(), nullable=False),
    sa.Column('current_hours', sa.Float(), nullable=False),
    sa.Column('deadline_ms', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BEATEN', 'FAILED', 'ABANDONED', name='bossfightstatus'), nullable=False),
    sa.Column('loot_type', sa.Enum('RUPEE_PAYOUT', 'MERCY_TOKEN', 'FREE_SCROLL', 'INTEREST_FREE', name='loottype'), nullable=False),
    sa.Column('loot_value', sa.Integer(), nullable=False),
    sa.Column('loot_awarded', sa.Boolean(), nullable=False),
    sa.Column('loot_ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('beaten_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('failed_at_ms', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes_worked', sa.Integer(), nullable=False),
    sa.Column('amount_earned', sa.Integer(), nullable=False),
    sa.Column('amount_spent', sa.Integer(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('earning_multiplier', sa.Float(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('mercy_tokens', sa.Integer(), nullable=False),
    sa.Column('target_hit', sa.Boolean(), nullable=False),
    sa.Column('lazy_tax_applied', sa.Boolean(), nullable=False),
    sa.Column('step_income_credited', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('device_heartbeats',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('last_seen_ms', sa.BigInteger(), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=False),
    sa.Column('is_charging', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('distraction_rules',
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('app_label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('SOCIAL', 'ENTERTAINMENT', 'SHOPPING', 'GAMING', 'OTHER', name='appcategory'), nullable=False),
    sa.Column('cost_per_minute', sa.Integer(), nullable=False),
    sa.Column('surge_cost_per_minute', sa.Integer(), nullable=False),
    sa.Column('monthly_cap_minutes', sa.Integer(), nullable=False),
    sa.Column('is_surge_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('package_name')
    )
    op.create_table('evidence_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_description', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('claimed_amount', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('approved_amount', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('NFC', 'SMS_UPI', 'NOTIFICATION_UPI', 'DISTRACTION', 'OATH_LOAN', 'OATH_INTEREST', 'LAZY_TAX', 'STEP_INCOME', 'MANUAL', 'BOSS_REWARD', 'REVERSAL', 'SURGE', 'MERCY_SPEND', 'OATH', 'OATH_REPAY', name='ledgercategory'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('merchant_name', sa.String(length=100), nullable=True),
    sa.Column('spend_class', sa.Enum('ESSENTIAL', 'DISCRETIONARY', 'UNKNOWN', name='spendclass'), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=True),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('is_disputed', sa.Boolean(), nullable=False),
    sa.Column('linked_dispute_id', sa.BigInteger(), nullable=True),
    sa.Column('is_verified_by_ai', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index('idx_ledger_category', 'ledger_entries', ['category'], unique=False)
    op.create_index('idx_ledger_disputed', 'ledger_entries', ['is_disputed'], unique=False)
    op.create_index('idx_ledger_timestamp', 'ledger_entries', ['timestamp_ms'], unique=False)
    op.create_table('nfc_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('tag_label', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('base_earned', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('final_earned', sa.Integer(), nullable=True),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oaths',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('initial_loan_amount', sa.Integer(), nullable=False),
    sa.Column('current_debt_amount', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(length=500), nullable=False),
    sa.Column('due_date_ms', sa.BigInteger(), nullable=False),
    sa.Column('daily_interest_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OVERDUE', 'REPAID_EARLY', 'REPAID_ON_TIME', 'DEFAULTED', name='oathstatus'), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('repaid_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('credit_score_delta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_caps',
    sa.Column('category', sa.Enum('SOCIAL', 'ENTERTAINMENT', 'SHOPPING', 'GAMING', 'OTHER', name='appcategory'), nullable=False),
    sa.Column('monthly_cap_rupees', sa.Integer(), nullable=False),
    sa.Column('current_month_spent', sa.Integer(), nullable=False),
    sa.Column('reset_day_of_month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('usage_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('period_start_ms', sa.BigInteger(), nullable=False),
    sa.Column('period_end_ms', sa.BigInteger(), nullable=False),
    sa.Column('app_usages_json', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_snapshots')
    op.drop_table('spending_caps')
    op.drop_table('oaths')
    op.drop_table('nfc_sessions')
    op.drop_index('idx_ledger_timestamp', table_name='ledger_entries')
    op.drop_index('idx_ledger_disputed', table_name='ledger_entries')
    op.drop_index('idx_ledger_category', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('evidence_submissions')
    op.drop_table('distraction_rules')
    op.drop_table('device_heartbeats')
    op.drop_table('daily_stats')
    op.drop_table('boss_fights')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
