"""add_deductions_wellness_suggestions

Revision ID: f0465acc6410
Revises: 03bdf2d7f0c4
Create Date: 2026-06-11 16:22:42.545472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0465acc6410'
down_revision: Union[str, None] = '03bdf2d7f0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('earned_amount', sa.Integer(), nullable=False),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_deductions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ai_verdict', sa.String(length=50), nullable=True),
    sa.Column('ai_reasoning', sa.String(length=500), nullable=True),
    sa.Column('ai_suggested_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_AI', 'APPROVED', 'REJECTED', 'OVERRIDDEN', name='deductionstatus'), nullable=False),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('submitted_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('override_tax_paid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_suggestions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('target_package', sa.String(length=200), nullable=True),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('suggested_value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('impact', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sleep_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('wake_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('quality', sa.Enum('EXCELLENT', 'GOOD', 'ADEQUATE', 'POOR', 'BAD', name='sleepquality'), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('multiplier_effect', sa.Float(), nullable=True),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_sessions')
    op.drop_table('rate_suggestions')
    op.drop_table('manual_deductions')
    op.drop_table('exercise_sessions')
    # ### end Alembic commands ###
