"""add_marketplace

Revision ID: f4351477f291
Revises: 30033544869b
Create Date: 2026-06-11 09:21:16.856884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4351477f291'
down_revision: Union[str, None] = '30033544869b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_passes',
    sa.Column('pass_type', sa.Enum('MOVIE', 'GAMING', 'BINGE', 'NAP', 'STUDY_BREAK', 'RESTAURANT', 'WEEKEND_OUTING', 'BOOK_PURCHASE', 'WEEKEND_MODE', 'VACATION_MODE', name='passtype'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('TIME', 'ACTIVITY', 'COOLDOWN', name='passcategory'), nullable=False),
    sa.Column('virtual_price', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('min_balance_after_purchase', sa.Integer(), nullable=False),
    sa.Column('min_work_hours_today', sa.Float(), nullable=False),
    sa.Column('requires_no_overdue_oaths', sa.Boolean(), nullable=False),
    sa.Column('min_streak_to_unlock', sa.Integer(), nullable=False),
    sa.Column('weekly_purchase_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_spend_cap_shared', sa.Boolean(), nullable=False),
    sa.Column('valid_after_hour', sa.Integer(), nullable=False),
    sa.Column('valid_before_hour', sa.Integer(), nullable=False),
    sa.Column('valid_on_weekends_only', sa.Boolean(), nullable=False),
    sa.Column('blocked_during_study_hours', sa.Boolean(), nullable=False),
    sa.Column('cooldown_hours_after_use', sa.Integer(), nullable=False),
    sa.Column('is_stackable_with_loot', sa.Boolean(), nullable=False),
    sa.Column('guilt_tax_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('pass_type')
    )
    op.create_table('purchased_passes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pass_type', sa.Enum('MOVIE', 'GAMING', 'BINGE', 'NAP', 'STUDY_BREAK', 'RESTAURANT', 'WEEKEND_OUTING', 'BOOK_PURCHASE', 'WEEKEND_MODE', 'VACATION_MODE', name='passtype'), nullable=False),
    sa.Column('status', sa.Enum('PURCHASED', 'ACTIVE', 'EXPIRED', 'CONSUMED', 'CANCELLED', name='passstatus'), nullable=False),
    sa.Column('category', sa.Enum('TIME', 'ACTIVITY', 'COOLDOWN', name='passcategory'), nullable=False),
    sa.Column('virtual_price_paid', sa.Integer(), nullable=False),
    sa.Column('guilt_tax_paid', sa.Integer(), nullable=False),
    sa.Column('ledger_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('purchased_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('activated_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('expires_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('consumed_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('matched_upi_dedup_key', sa.String(length=64), nullable=True),
    sa.Column('loot_bonus_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pass_status', 'purchased_passes', ['status'], unique=False)
    op.create_index('idx_pass_type_purchased', 'purchased_passes', ['pass_type', 'purchased_at_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pass_type_purchased', table_name='purchased_passes')
    op.drop_index('idx_pass_status', table_name='purchased_passes')
    op.drop_table('purchased_passes')
    op.drop_table('marketplace_passes')
    # ### end Alembic commands ###
