/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OathsRouteImport } from './routes/oaths'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as DistractionRouteImport } from './routes/distraction'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OathsRoute = OathsRouteImport.update({
  id: '/oaths',
  path: '/oaths',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const DistractionRoute = DistractionRouteImport.update({
  id: '/distraction',
  path: '/distraction',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/distraction': typeof DistractionRoute
  '/focus': typeof FocusRoute
  '/ledger': typeof LedgerRoute
  '/marketplace': typeof MarketplaceRoute
  '/oaths': typeof OathsRoute
  '/settings': typeof SettingsRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/distraction': typeof DistractionRoute
  '/focus': typeof FocusRoute
  '/ledger': typeof LedgerRoute
  '/marketplace': typeof MarketplaceRoute
  '/oaths': typeof OathsRoute
  '/settings': typeof SettingsRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/distraction': typeof DistractionRoute
  '/focus': typeof FocusRoute
  '/ledger': typeof LedgerRoute
  '/marketplace': typeof MarketplaceRoute
  '/oaths': typeof OathsRoute
  '/settings': typeof SettingsRoute
  '/wellness': typeof WellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/distraction'
    | '/focus'
    | '/ledger'
    | '/marketplace'
    | '/oaths'
    | '/settings'
    | '/wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/distraction'
    | '/focus'
    | '/ledger'
    | '/marketplace'
    | '/oaths'
    | '/settings'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/distraction'
    | '/focus'
    | '/ledger'
    | '/marketplace'
    | '/oaths'
    | '/settings'
    | '/wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DistractionRoute: typeof DistractionRoute
  FocusRoute: typeof FocusRoute
  LedgerRoute: typeof LedgerRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OathsRoute: typeof OathsRoute
  SettingsRoute: typeof SettingsRoute
  WellnessRoute: typeof WellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oaths': {
      id: '/oaths'
      path: '/oaths'
      fullPath: '/oaths'
      preLoaderRoute: typeof OathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distraction': {
      id: '/distraction'
      path: '/distraction'
      fullPath: '/distraction'
      preLoaderRoute: typeof DistractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DistractionRoute: DistractionRoute,
  FocusRoute: FocusRoute,
  LedgerRoute: LedgerRoute,
  MarketplaceRoute: MarketplaceRoute,
  OathsRoute: OathsRoute,
  SettingsRoute: SettingsRoute,
  WellnessRoute: WellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
